local project = require("viteenv.project")

describe("project.root_for", function()
  it("finds the nearest vite config ancestor", function()
    local d = H.tmpdir()
    H.write(d .. "/proj/vite.config.ts", "export default {}\n")
    H.write(d .. "/proj/src/deep/x.ts", "//\n")
    eq(H.norm(project.root_for(d .. "/proj/src/deep/x.ts")), H.norm(d .. "/proj"))
  end)

  it("falls back to the nearest package.json", function()
    local d = H.tmpdir()
    H.write(d .. "/app/package.json", "{}\n")
    H.write(d .. "/app/src/y.ts", "//\n")
    eq(H.norm(project.root_for(d .. "/app/src/y.ts")), H.norm(d .. "/app"))
  end)

  it("prefers a vite config over a deeper-less package.json", function()
    local d = H.tmpdir()
    H.write(d .. "/mono/package.json", "{}\n")
    H.write(d .. "/mono/pkg/vite.config.ts", "export default {}\n")
    H.write(d .. "/mono/pkg/src/z.ts", "//\n")
    eq(H.norm(project.root_for(d .. "/mono/pkg/src/z.ts")), H.norm(d .. "/mono/pkg"))
  end)

  it("returns nil when nothing is found", function()
    local d = H.tmpdir()
    H.write(d .. "/lonely/file.ts", "//\n")
    eq(project.root_for(d .. "/lonely/file.ts"), nil)
  end)
end)
